version: '3.4'

services:

  node:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: python manage.py run
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      DEBUG: 1